import '../styles/globals.scss';
import type { Metadata } from 'next';
import { Provider } from '../utils/provider';
import NextTopLoader from 'nextjs-toploader';
import { Inter } from 'next/font/google';
import { cn } from '@expense-management/frontend/lib/utils';

const inter = Inter({
  subsets: ['latin'],
  weight: '400',
});
export const metadata: Metadata = {
  title: 'Lâm Việt Cường',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log('1231232312312', process.env.NEXT_PUBLIC_BASE_URL);

  return (
    <html suppressHydrationWarning lang="en">
      <body className={cn('min-h-screen bg-background antialiased')}>
        <Provider>
          <NextTopLoader crawlSpeed={0} crawl={false} />
          <main className={inter.className}>{children}</main>
        </Provider>
      </body>
    </html>
  );
}
